-- SQL statements which are executed at application startup if hibernate.hbm2ddl.auto is 'create' or 'create-drop'

DELETE FROM "PUBLIC"."MOVIMENTACAOITEMESTOQUE";
DELETE FROM "PUBLIC"."ITEMESTOQUE";
DELETE FROM "PUBLIC"."TIPOCATEGORIA";
DELETE FROM "PUBLIC"."UNIDADEMEDIDA";

INSERT INTO "PUBLIC"."UNIDADEMEDIDA" ( "ID", "CODIGO", "DESCRICAO" ) VALUES (100 , 'KG', 'Quilograma(s)');
INSERT INTO "PUBLIC"."UNIDADEMEDIDA" ( "ID", "CODIGO", "DESCRICAO" ) VALUES (101, 'UN', 'Unidade(s)');
INSERT INTO "PUBLIC"."UNIDADEMEDIDA" ( "ID", "CODIGO", "DESCRICAO" ) VALUES (102, 'L', 'Litro(s)');
INSERT INTO "PUBLIC"."UNIDADEMEDIDA" ( "ID", "CODIGO", "DESCRICAO" ) VALUES (103, 'M', 'Metro(s)');

INSERT INTO "PUBLIC"."TIPOCATEGORIA" ( "ID", "CODIGO", "DESCRICAO" ) VALUES (100 , 'A', 'Categoria A');
INSERT INTO "PUBLIC"."TIPOCATEGORIA" ( "ID", "CODIGO", "DESCRICAO" ) VALUES (101 , 'B', 'Categoria B');
INSERT INTO "PUBLIC"."TIPOCATEGORIA" ( "ID", "CODIGO", "DESCRICAO" ) VALUES (102 , 'C', 'Categoria C');
INSERT INTO "PUBLIC"."TIPOCATEGORIA" ( "ID", "CODIGO", "DESCRICAO" ) VALUES (103 , 'D', 'Categoria D');

INSERT INTO "PUBLIC"."ITEMESTOQUE" ( "ID", "CODIGO", "DESCRICAO", "TIPOCATEGORIA_ID", "UNIDADEMEDIDA_ID" ) VALUES ( 100 , '1000', 'Cadeira A', 100, 101);
INSERT INTO "PUBLIC"."ITEMESTOQUE" ( "ID", "CODIGO", "DESCRICAO", "TIPOCATEGORIA_ID", "UNIDADEMEDIDA_ID" ) VALUES ( 101 , '1001', 'Cadeira B', 101, 101);
INSERT INTO "PUBLIC"."ITEMESTOQUE" ( "ID", "CODIGO", "DESCRICAO", "TIPOCATEGORIA_ID", "UNIDADEMEDIDA_ID" ) VALUES ( 102 , '1002', 'Cadeira C', 102, 101);
INSERT INTO "PUBLIC"."ITEMESTOQUE" ( "ID", "CODIGO", "DESCRICAO", "TIPOCATEGORIA_ID", "UNIDADEMEDIDA_ID" ) VALUES ( 103 , '1003', 'Cadeira D', 103, 101);
INSERT INTO "PUBLIC"."ITEMESTOQUE" ( "ID", "CODIGO", "DESCRICAO", "TIPOCATEGORIA_ID", "UNIDADEMEDIDA_ID" ) VALUES ( 104 , '1004', 'Mesa A', 100, 101);
INSERT INTO "PUBLIC"."ITEMESTOQUE" ( "ID", "CODIGO", "DESCRICAO", "TIPOCATEGORIA_ID", "UNIDADEMEDIDA_ID" ) VALUES ( 105 , '1005', 'Mesa B', 101, 101);
INSERT INTO "PUBLIC"."ITEMESTOQUE" ( "ID", "CODIGO", "DESCRICAO", "TIPOCATEGORIA_ID", "UNIDADEMEDIDA_ID" ) VALUES ( 106 , '1006', 'Mesa C', 102, 101);
INSERT INTO "PUBLIC"."ITEMESTOQUE" ( "ID", "CODIGO", "DESCRICAO", "TIPOCATEGORIA_ID", "UNIDADEMEDIDA_ID" ) VALUES ( 107 , '1007', 'Mesa D', 103, 101);